### ISSUE TITLE
[2.13.6] Generic type 'StoreEnhancer' requires 1 type argument(s).

### ISSUE THREAD

**Issue by adavidof** [zalmoxisus/redux-devtools-extension#584]
redux-devtools-extension: `2.13.6`

node_modules/redux-devtools-extension/index.d.ts:159:73 - error TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).

159 export function composeWithDevTools<StoreExt, StateExt>(...funcs: Array<StoreEnhancer<StoreExt, StateExt>>): StoreEnhancer<StoreExt, StateExt>;
                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


node_modules/redux-devtools-extension/index.d.ts:159:110 - error TS2314: Generic type 'StoreEnhancer' requires 1 type argument(s).

159 export function composeWithDevTools<StoreExt, StateExt>(...funcs: Array<StoreEnhancer<StoreExt, StateExt>>): StoreEnhancer<StoreExt, StateExt>;
                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

in redux-devtools-extension `2.13.5` all is fine

**Comment by zalmoxisus** [comment]
It was introduced in #578. Maybe @scally knows what an be the issue

**Comment by JPeer264** [comment]
If the typings get changed to `StoreEnhancer<StoreExt>` instead of `StoreEnhancer<StoreExt, StoreExt>` (doubled types) it got fixed.

**Comment by adavidof** [comment]
@JPeer264 
yes, so it should be changed in `redux-devtools-extension` repo

**Comment by zalmoxisus** [comment]
I published `2.13.7`, should be fixed now. Thanks @JPeer264 for the contribution!
