### ISSUE TITLE
debug_session with immutable.js

### ISSUE THREAD

**Issue by zivni** [zalmoxisus/redux-devtools-extension#53]
It seems that after the[ immutable.js fix 35](https://github.com/zalmoxisus/redux-devtools-extension/issues/35) every thing get serialized  to plain JS. but now when using ?debug_session=ds, it doesn't deserialized back to immutable.js and i'm getting `.get is not a function`.

Is there a way to tell the extension to deserialize back to immutable.js, and still keep the state in the panes plain JS?

**Comment by zalmoxisus** [comment]
The extension shouldn't send back anything, it just gets changes from the lifted store, and dispatch actions to the lifted store in order to change anything. Default serialization introduced in #35, can be disabled in settings, but that problem you described comes not from the extension's serializations, but from [`persistState`'s](https://github.com/gaearon/redux-devtools/blob/master/src/persistState.js#L31).

The solution would be to remove ['persistState' from the extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/store/configureStore.js#L7-L9), so you'll be able to import it from `redux-devtools` and pass your `deserializeState` function, but [I'm not sure that will help](https://github.com/gaearon/redux-devtools/issues/108), will it?.

**Comment by ganmor** [comment]
I got it working by passing down the following deserialisation function to persistState

```
compose(
    instrument(subscriber),
    persistState(
      getPersistSession(),
      (data) => { return  data ? Object.keys(data).map( dataKey => { return Immutable.fromJS(data[dataKey])}) : data }
    )
  )(next);
```

for now I am running the extension locally but maybe we could do something like this: 

```
compose(
    instrument(subscriber),
    persistState(
      getPersistSession(),
      window.devToolDeserialiseFunc
    )
  )(next);
```
where devToolDeserialiseFunc have to be in the window otherwise persist state would just use identity like it does now

`persistState(sessionId, deserializeState = identity, deserializeAction = identity) {`

**Comment by zalmoxisus** [comment]
I think we could pass the deserialisation function to the extension like so:
```js
window.devToolsExtension({ devToolDeserialiseFunc });
```
This function can be used not only for the `persistState` but also when importing state history from a file (after implementing #51).

Another option would be to have this function inside the extension (avoiding boilerplate) and pass a flag which will require it as
```js
window.devToolsExtension({ isImmutableJS });
```

**Comment by ganmor** [comment]
If you want to package the function with the extension you'd have to package immutable too, I am not sure it's a good option.
I think the first solution is better.

I'd be happy to submit a PR including:
- The proposed change to window.devToolsExtension
- An example of the function in the README

Also it would be great to output a warning refering to the readme if we try to serialize immutable data.


For the recored redux persist solves this be triggering an event when deserializing data. This event can be caught by the reducers to regenerate data
 [see](https://github.com/rt2zz/redux-persist/blob/1ed523f52824aaa0b94e4b44550b51745f5b6e05/src/persistStore.js)
But that would be some code in the reducers just to handle debugging.

**Comment by zalmoxisus** [comment]
Agree, we don't want to package and inject Immutable.js in every page. Growing the injected script size would lead to a latency in loading and the store will be created before the `window.devToolsExtension` is injected.

Using the extension as `window.devToolsExtension({ deserialize:  state =>  Immutable.fromJS(state) })` would be pretty neat. The PR would be welcome. Also the parameter should be specified in the [API section](https://github.com/zalmoxisus/redux-devtools-extension#api) (we have `name` parameter there).

**Comment by zalmoxisus** [comment]
Implemented in #65. Should work in `1.0.0.8`, thanks to @minedeljkovic.

Please see [the API section](https://github.com/zalmoxisus/redux-devtools-extension#api) and give it a try.
